### ISSUE TITLE
Could I launch 2 instance of same game? (multiboxing)

### ISSUE THREAD

**Issue by ghost** [Open-Wine-Components/umu-launcher#85]
I used WINE-GE to play Turtle WoW (https://turtle-wow.org/)

Then today I switched to umu-launcher and Proton-GE finding that I can no longer multiboxing anymore, if I try launching 2nd game instance, it froze after showing ProtonFixes text. No error but the game won't start.

Is there anything I could try?

**Comment by R1kaB3rN** [comment]
By default, umu does not allow users to run more than 1 game in the same prefix at once. As for why, see https://github.com/Open-Wine-Components/umu-launcher/issues/79#issuecomment-2035461310

If you're using Lutris, I believe you will need to specify this environment variable `PROTON_VERB=runinprefix` when umu is configured as the runner.

![example](https://github.com/Open-Wine-Components/umu-launcher/assets/100738684/51797ede-6bf5-4c7b-90f7-7627c8f1bf71)

**Comment by ghost** [comment]
> By default, umu does not allow users to run more than 1 game in the same prefix at once. As for why, see [#79 (comment)](https://github.com/Open-Wine-Components/umu-launcher/issues/79#issuecomment-2035461310)

I see it's by design. I now have 2 prefix for the same game, it works now. Thanks, I'll close this issue as solved.
